# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

std_c <- function(x) {
    .Call(`_sglasso_std_c`, x)
}

lambda_max_c <- function(Xtilde, Ytilde, K, K1) {
    .Call(`_sglasso_lambda_max_c`, Xtilde, Ytilde, K, K1)
}

gd_sglasso_ssr <- function(Xtilde, Ytilde, lambda, lambda_max, d, alpha, K, K1, K0, gm, beta_start, max_iter, eps, dfmax, gmax) {
    .Call(`_sglasso_gd_sglasso_ssr`, Xtilde, Ytilde, lambda, lambda_max, d, alpha, K, K1, K0, gm, beta_start, max_iter, eps, dfmax, gmax)
}

